# Generated by Django 4.1.6 on 2023-02-05 17:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('epfApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='income_and_expenses',
        ),
        migrations.AddField(
            model_name='customer',
            name='excel_file',
            field=models.FileField(default=django.utils.timezone.now, upload_to='excel/'),
            preserve_default=False,
        ),
    ]
